from .structureadaptortestcase import StructureAdaptorTestCase
from .biomoleculeadaptortestcase import BiomoleculeAdaptorTestCase
from .chainadaptortestcase import ChainAdaptorTestCase
from .residueadaptortestcase import ResidueAdaptorTestCase
from .atomadaptortestcase import AtomAdaptorTestCase
from .contactadaptortestcase import ContactAdaptorTestCase
from .interfaceadaptortestcase import InterfaceAdaptorTestCase
from .protfragmentadaptortestcase import ProtFragmentAdaptorTestCase
from .aromaticringadaptortestcase import AromaticRingAdaptorTestCase
from .ringinteractionadaptortestcase import RingInteractionAdaptorTestCase
from .ligandadaptortestcase import LigandAdaptorTestCase
from .chemcompadaptortestcase import ChemCompAdaptorTestCase
from .fragmentadaptortestcase import FragmentAdaptorTestCase

from .siftadaptortestcase import SIFtAdaptorTestCase
from .ligandmatchadaptortestcase import LigandMatchAdaptorTestCase
